/* eslint-disable prettier/prettier */

import HeroSection from "@/components/HeroSection";
import FaqSection from "@/components/service-sections/FaqSection";
import WhoThisIsForSection from "@/components/service-sections/WhoThisIsFor";
import ProcessSection, { ProcessStep } from "@/components/service-sections/ProcessSection";
import Container from "@/components/ui/Container";
import WhyServiceWorksSection from "@/components/service-sections/WhyServiceWorksSection";



const webWhyContent = {
  heading: "Why Content Marketing Strategy Still Works(When Done",
  highlight: "Right)",
  paragraph1:
    "Many businesses treat content like a checklist. But strategic content marketing is your silent salesperson—it builds trust, boosts SEO, and positions your brand as the go-to expert.",
  paragraph2:
    "When done right, content becomes your most scalable and cost-effective marketing channel.",
  stats: [
    { value: "72%", label: "of marketers say content boosts engagement" },
    { value: "3x", label: "more leads generated by content vs. traditional ads" },
    { value: "47%", label: "of buyers consume 3–5 pieces of content before talking to sales" },
    { value: "90%", label: "of consumers expect brands to deliver useful content" },
  ],
};

/* Removed duplicate processSteps declaration to fix redeclaration error */

const steps: ProcessStep[] = [
  {
    icon: <p>💡</p>,
    title: " V — Visual Discovery",
    description:
      "We kick things off by diving deep into your brand, goals, and audience. We gather references, vibe-check your competition, and understand what truly sets you apart.",
  },
  {
    icon: <p>🎨</p>,
    title: " I — Idea Sketching",
    description:
      "From messy brainstorms to polished concepts — we sketch out design directions that align with your message and aesthetics.",
  },
  {
    icon: <p>⚙️</p>,
    title: " B — Build & Design",
    description:
      "We bring your vision to life with strategic layouts, striking visuals, and pixel-perfect design — whether it’s social content, print material, or digital assets.",
  },
  {
    icon: <p>🔁</p>,
    title: " E — Edit & Evolve",
    description:
      "Your feedback powers the final polish. We refine, revise, and deliver designs that hit the mark and are ready to go live across all channels.",
  },
];

// why funnel mapping works objects 

// Define the Feature type
type Feature = {
  emoji: string;
  title: string;
  description: string;
};

const features: Feature[] = [
  {
    emoji: "🧠",
    title: "Design = First Impressions",
    description: "Your visual identity is the first thing people notice. Make it unforgettable.",
  },
  {
    emoji: "📱",
    title: " Content is Scrolled, Design is Paused",
    description: "A bold graphic can stop the scroll and earn the click.",
  },
  {
    emoji: "💡",
    title: " Clarity Drives Action",
    description: "Great design communicates your message clearly and quickly — no confusion, no friction.",
  },
  {
    emoji: "🎯",
    title: " On-Brand, Every Time",
    description: "Consistent visuals help build trust, recognition, and authority across every channel.",
  },
  {
    emoji: "💰",
    title: " It Impacts Conversions",
    description: "Whether it’s an ad, landing page, or sales deck — strong design boosts performance.",
  },
];


export const revalidate = 3600; // Rebuild every hour

export default async function IndexPage() {
  return (
    <>
      <HeroSection 
      badgeText="Content that winds customers" // Optional badge text
        headlineText1="🎨 Graphics"
        headlineText2="That Speak"
        headlineText3="Louder Than Words"
        primaryButtonText="📥 Let's Design Powerful"
        primaryButtonUrl="/strategy-session"
        secondaryButtonText="📄 See Our Process"
        secondaryButtonUrl="#our-process-graphic"
        subheading="From scroll-stopping social media posts to brand-defining visuals — we create designs that don’t just look good, they perform.
"
      />
      <Container>
       <WhyServiceWorksSection
        features={features}
        heading="Why Graphic Design Works"
        subheading="If you know how to do them"
      />

      </Container>
      <div className="div" id="our-process-graphic">

      
      <ProcessSection
        heading="✨ The VIBE Method"
        steps={steps}
        subheading="A 4-step breakdown with a catchy name and personality"
      />
  </div>
      <Container>
        
      <WhoThisIsForSection
      heading="Who This Is For"
      highlightedPhrases={[
        " If you’re looking for truly strategic, high-performing design work”",
        " — whether it’s for a campaign, a pitch,",
        "or your brand identity — we might just be your people.,”",
        "We work best with clients who value collaboration, ",
        "care about design that drives results,",
        "and aren’t afraid to push creative boundaries. ",
        "If you’re serious about leveling up your visual game — we’re here to make it happen. 🎯"
      ]}
      introText="We’re not the kind of team that just throws together Canva templates and calls it a day."
      subheading="we build strategic ones that drive results."
    />
   </Container>
      

 
   
  <Container>
      <FaqSection
  ctaText="📩 Need Custom Advice?"
  eyebrow="❓ FAQs about Our Funnel Mapping Service"
  faqs={[
    {
      question: "Q: Is this just a diagram?",
      answer:
        "Nope! You’ll get a full breakdown of your customer journey, messaging flow, traffic plan, and key conversion points—not just a pretty flowchart.",
    },
    {
      question: "Q: Do you help build the funnel too?",
      answer:
        "Yes, that’s available as an add-on. We can help implement your funnel on platforms like ClickFunnels, WordPress, Webflow, or even via email automations.",
    },
     {
      question: "Q: What if I don’t have any funnel yet?",
      answer:
        "Even better! We’ll help you craft your funnel from scratch, based on your goals, audience, and offer.",
    },
    {
      question: "Q: Can you revise the funnel after delivery?",
      answer:
        "Absolutely. Each package includes 1 round of revisions. Additional strategy support is also available if needed.",
    },

  ]}
  heading="Still Wondering If It Works?"
  subheading="We’ve helped dozens of brands run profitable campaigns. Here are answers to the most common questions people ask before they sign up."
/>
</Container>
 {/* <Container>
      <CTABottomSection firstbuttontext={"👉 Book a Consultation"} 
      heading={"Ready to Turn Clicks Into Clients?"} 
      subheading={"Your funnel isn’t just a path—it’s your profit engine. Whether you’re stuck with scattered tools or just getting started, we’ll help you make sense of the chaos and create a clear, high-converting system."} />
  </Container> */}
    </>
  );
}
