/* eslint-disable prettier/prettier */
import { MagnifyingGlassIcon, UserGroupIcon, DocumentTextIcon, RocketLaunchIcon } from "@heroicons/react/24/outline";

import HeroSection from "@/components/HeroSection";
import FaqSection from "@/components/service-sections/FaqSection";
import WhoThisIsForSection from "@/components/service-sections/WhoThisIsFor";
import ProcessSection, { ProcessStep } from "@/components/service-sections/ProcessSection";
import Container from "@/components/ui/Container";
import WhyFunnelMappingWorksSection from "@/components/service-sections/WhyServiceWorksSection";

const webWhyContent = {
  heading: "Why Content Marketing Strategy Still Works(When Done",
  highlight: "Right)",
  paragraph1:
    "Many businesses treat content like a checklist. But strategic content marketing is your silent salesperson—it builds trust, boosts SEO, and positions your brand as the go-to expert.",
  paragraph2:
    "When done right, content becomes your most scalable and cost-effective marketing channel.",
  stats: [
    { value: "72%", label: "of marketers say content boosts engagement" },
    { value: "3x", label: "more leads generated by content vs. traditional ads" },
    { value: "47%", label: "of buyers consume 3–5 pieces of content before talking to sales" },
    { value: "90%", label: "of consumers expect brands to deliver useful content" },
  ],
};

/* Removed duplicate processSteps declaration to fix redeclaration error */

const steps: ProcessStep[] = [
  {
    icon: <MagnifyingGlassIcon className="w-8 h-8 text-blue-600" />,
    title: "F — Funnel Audit",
    description:
      "We start by analyzing what’s already working (or not). Whether you have an existing funnel or you're starting from scratch, we’ll pinpoint key areas to fix or build from.",
  },
  {
    icon: <UserGroupIcon className="w-8 h-8 text-pink-500" />,
    title: "A — Audience Journey Design",
    description:
      "From cold to hot, we craft a step-by-step customer path—from awareness to action. Every touchpoint is mapped to match your buyer psychology.",
  },
  {
    icon: <DocumentTextIcon className="w-8 h-8 text-purple-600" />,
    title: "S — Strategy Blueprint",
    description:
      "We don’t just draw diagrams—we create your funnel playbook. This includes messaging flow, content, channel strategy, and key triggers that move people forward.",
  },
  {
    icon: <RocketLaunchIcon className="w-8 h-8 text-green-600" />,
    title: "T — Tactical Activation Plan",
    description:
      "Once the funnel is mapped, we hand over a ready-to-implement plan or help you build it—whether it's for a landing page, ad sequence, or email automation.",
  },
];

// why funnel mapping works objects 

// Define the Feature type
type Feature = {
  emoji: string;
  title: string;
  description: string;
};

const features: Feature[] = [
  {
    emoji: "🧩",
    title: "Clarity",
    description: "Get a crystal-clear view of how your leads move—from discovery to conversion—and where opportunities are being missed.",
  },
  {
    emoji: "📈",
    title: "Optimization",
    description: "Stop guessing. With your funnel mapped out, we can plug leaks, refine CTAs, and eliminate bottlenecks.",
  },
  {
    emoji: "💸",
    title: "Higher ROI",
    description: "When every step flows logically, your conversions increase, cost per acquisition drops, and every ad or content piece works harder.",
  },
  {
    emoji: "🛠️",
    title: "Strategy-First Approach",
    description: "We don’t just “build funnels.” We align your funnel with your business goals, customer behavior, and marketing channels for max impact.",
  },
  {
    emoji: "🧠",
    title: "Custom-Tailored to You",
    description: "Whether you're running ads, organic traffic, or email campaigns—we design the right funnel for your unique growth model.",
  },
];

export const revalidate = 3600; // Rebuild every hour

export default async function IndexPage() {
  return (
    <>
      <HeroSection
        badgeText="Content that winds customers" // Optional badge text
        headlineText1="🎯 Map the "
        headlineText2="Path."
        headlineText3="Maximize the Conversions."
        primaryButtonText="📥 Get You're Funnel Mapped"
        primaryButtonUrl="/strategy-session"
        secondaryButtonText="📄 See Our Process"
        secondaryButtonUrl="/contact"
        subheading="Your marketing funnel is only as strong as the strategy behind it. We help you visually map, optimize, and build every step of your buyer journey—so more visitors turn into leads, and more leads turn into customers.
"
      />
      <Container>
        <WhyFunnelMappingWorksSection
          features={features}
          heading="Why Funnel Mapping Works"
          subheading="We’ve designed a 4-step framework to map, design, and optimize funnels that convert. Here's how it works:"
        />

      </Container>
      <ProcessSection
        heading="Our Process: The F.A.S.T. Funnel Method"
        steps={steps}
        subheading="We’ve designed a 4-step framework to map, design, and optimize funnels that convert. Here's how it works:"
      />

      <Container>

        <WhoThisIsForSection
          heading="Who This Is For"
          highlightedPhrases={[
            " If you’re just looking to “fill your blog”",
            " or copy what your competitors are doing—this might not be the right fit.",
            "If you’re serious about building,”",
            "a content system that drives traffic, ",
            " builds authority,",
            "grow your business — ",
            "and generates leads on autopilot—then we just might be the perfect content partner."
          ]}
          introText="We’re not the team that pumps out generic content with zero strategy."
          subheading="we build strategic ones that drive results."
        />
      </Container>




      <Container>
        <FaqSection
          ctaText="📩 Need Custom Advice?"
          eyebrow="❓ FAQs about Our Funnel Mapping Service"
          faqs={[
            {
              question: "Q: Is this just a diagram?",
              answer:
                "Nope! You’ll get a full breakdown of your customer journey, messaging flow, traffic plan, and key conversion points—not just a pretty flowchart.",
            },
            {
              question: "Q: Do you help build the funnel too?",
              answer:
                "Yes, that’s available as an add-on. We can help implement your funnel on platforms like ClickFunnels, WordPress, Webflow, or even via email automations.",
            },
            {
              question: "Q: What if I don’t have any funnel yet?",
              answer:
                "Even better! We’ll help you craft your funnel from scratch, based on your goals, audience, and offer.",
            },
            {
              question: "Q: Can you revise the funnel after delivery?",
              answer:
                "Absolutely. Each package includes 1 round of revisions. Additional strategy support is also available if needed.",
            },

          ]}
          heading="Still Wondering If It Works?"
          subheading="We’ve helped dozens of brands run profitable campaigns. Here are answers to the most common questions people ask before they sign up."
        />
      </Container>
      {/*  <Container>
      <CTABottomSection firstbuttontext={"👉 Book Funnel Strategy Call"} 
      heading={"Ready to Turn Clicks Into Clients?"} 
      subheading={"Your funnel isn’t just a path—it’s your profit engine. Whether you’re stuck with scattered tools or just getting started, we’ll help you make sense of the chaos and create a clear, high-converting system."} />
  </Container> */}
    </>
  );
}
