/* eslint-disable prettier/prettier */
import HeroSection from "@/components/HeroSection";

import CTABottomSection from "@/components/CTA";
import WhyServiceWorks from "@/components/service-sections/WhyServiceWork";
import FaqSection from "@/components/service-sections/FaqSection";
import WhoThisIsForSection from "@/components/service-sections/WhoThisIsFor";
import FeaturedWebDesignPostsWrapper from "@/wrappers/FeaturedWebDesignPostsWrapper";
import OurProcess from "@/components/service-sections/ourprocess";

import Container from "@/components/ui/Container";

const webWhyContent = {
    heading: "Why Content Marketing Strategy Still Works(When Done",
    highlight: "Right)",
    paragraph1:
        "Many businesses treat content like a checklist. But strategic content marketing is your silent salesperson—it builds trust, boosts SEO, and positions your brand as the go-to expert.",
    paragraph2:
        "When done right, content becomes your most scalable and cost-effective marketing channel.",
    stats: [
        { value: "72%", label: "of marketers say content boosts engagement" },
        { value: "3x", label: "more leads generated by content vs. traditional ads" },
        { value: "47%", label: "of buyers consume 3–5 pieces of content before talking to sales" },
        { value: "90%", label: "of consumers expect brands to deliver useful content" },
    ],
};

const processSteps = [
    {
        id: 1,
        title: '📌 Step 1: Clarify the Goals',
        description: "We dig into your business model, audience, and revenue goals to craft a content strategy that aligns with what actually moves the needle.",
    },
    {
        id: 2,
        title: '🧠 Step 2: Optimize Your Topics',
        description: "We identify high-impact topics using SEO, market trends, and customer insights—ensuring every piece speaks to your audience and ranks.",
    },
    {
        id: 3,
        title: '✍️ Step 3: Refine & Create',
        description: "Our content team crafts compelling blog posts, lead magnets, guides, and more—designed to engage, educate, and convert.",
    },
    {
        id: 4,
        title: '📈 Step 4: Expand & Measure',
        description: "We distribute content across key platforms, track performance, and continuously optimize based on data and engagement.",
    },
];

export const revalidate = 3600; // Rebuild every hour

export default async function IndexPage() {
    return (
        <>
            <HeroSection
                badgeText="Content that winds customers" // Optional badge text
                headlineText1="Turn Content Into"
                headlineText2="Into"
                headlineText3="Customers"
                primaryButtonText="📥 Build Content Strategy"
                primaryButtonUrl="/strategy-session"
                secondaryButtonText="📄 See Our Process"
                secondaryButtonUrl="#our-process-content"
                subheading="We don’t just write blogs—we build content engines. With the right strategy, your content doesn’t just inform—it attracts, nurtures, and converts your ideal clients 24/7.

"
            />
            <Container>
                <WhyServiceWorks {...webWhyContent} />
            </Container>
            <OurProcess
                id="our-process-content"
                heading="Our Process – The CORE Framework 🧩"
                subheading="Content without strategy is just noise. Our proven CORE Framework ensures every piece of content works toward a clear, measurable goal."
                imageSrc="/page-content-images/seoservice-process.png" // Path to your image in the public folder
                imageAlt="Beautiful building with balconies"
                steps={processSteps}
            />
            <Container>
                <WhoThisIsForSection
                    heading="Who This Is For"
                    highlightedPhrases={[
                        " If you’re just looking to “fill your blog”",
                        " or copy what your competitors are doing—this might not be the right fit.",
                        "If you’re serious about building,”",
                        "a content system that drives traffic, ",
                        " builds authority,",
                        "grow your business — ",
                        "and generates leads on autopilot—then we just might be the perfect content partner."
                    ]}
                    introText="We’re not the team that pumps out generic content with zero strategy."
                    subheading="we build strategic ones that drive results."
                />
            </Container>




            <Container>
                <FaqSection
                    ctaText="📩 Need Custom Advice?"
                    eyebrow="❓ FAQs about Our Content Marketing Service"
                    faqs={[
                        {
                            question: "Q1: How long does it take to see results from content marketing?",
                            answer:
                                "A: Content marketing is a long-term game. While some traction begins in the first 30–60 days, real results—organic traffic, leads, conversions—compound over 3 to 6 months.",
                        },
                        {
                            question: "Q2: Do I need to be involved in the content creation process?",
                            answer:
                                "A: Only as much as you want to be. We handle strategy, writing, and publishing. You can review and give feedback—or leave it all to us.",
                        },
                        {
                            question: "Q3: What industries do you work with?",
                            answer:
                                "A: We work with startups, service-based businesses, tech companies, and more. If your business benefits from content-driven traffic or trust—we can help.",
                        },
                        {
                            question: "Q5: Can you help repurpose old content?",
                            answer:
                                "A: Yes! We can audit, update, and repurpose your existing content into SEO-friendly assets, social posts, and lead magnets.",
                        },

                    ]}
                    heading="Still Wondering If It Works?"
                    subheading="We’ve helped dozens of brands run profitable campaigns. Here are answers to the most common questions people ask before they sign up."
                />
            </Container>
            {/* <Container>
      <CTABottomSection firstbuttontext={"👉Plan Content Strategy"} heading={"Your audience is searching. Let’s make sure they find you"} subheading={"Whether you're starting from scratch or scaling up, our content strategies are built to drive traffic, earn trust, and convert leads."} />
  </Container> */}
        </>
    );
}
